Feature: Everything to do with ...

  Scenario: getting all ...
    Given The endpoint for "..." is available for method "GET"
    When I retrieve all ....
    Then I get a list of 3 ...
    And I get http status 200

  Scenario: Create ...
    Given The endpoint for "..." is available for method "POST"
    When ...
    Then I get http status 201
    And The price of the guitar is 0